create extension if not exists "pgcrypto";

alter table public.employees
  add column if not exists is_platform_admin boolean not null default false;
alter table public.employees drop column if exists admin_pin;

create table if not exists public.employee_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  client_id uuid not null references public.clients(id) on delete cascade,
  employee_id uuid not null references public.employees(id) on delete cascade,
  device_id text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_employee_sessions_token
  on public.employee_sessions(token_hash)
  where revoked_at is null;
create index if not exists idx_employee_sessions_employee_device
  on public.employee_sessions(employee_id, device_id, expires_at desc);

create table if not exists public.hoof_login_attempts (
  id bigint generated by default as identity primary key,
  client_id uuid references public.clients(id) on delete cascade,
  login_key text not null,
  ip_hash text not null,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);

create table if not exists public.hoof_manager_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  employee_session_id uuid not null references public.employee_sessions(id) on delete cascade,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.hoof_admin_audit (
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients(id) on delete cascade,
  employee_id uuid references public.employees(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_hoof_login_attempts_lookup
  on public.hoof_login_attempts(client_id, login_key, ip_hash, attempted_at desc);

alter table public.employee_sessions enable row level security;
alter table public.hoof_login_attempts enable row level security;
alter table public.hoof_manager_sessions enable row level security;
alter table public.hoof_admin_audit enable row level security;
revoke all on public.employee_sessions, public.hoof_login_attempts,
  public.hoof_manager_sessions, public.hoof_admin_audit from anon, authenticated;

create or replace function public.hoof_request_header(header_name text)
returns text
language sql
stable
as $$
  select (coalesce(nullif(current_setting('request.headers', true), ''), '{}')::jsonb ->> lower(header_name));
$$;

create or replace function public.hoof_current_session()
returns setof public.employee_sessions
language sql
stable
security definer
set search_path = public, extensions
as $$
  select session.*
  from public.employee_sessions session
  where session.token_hash = encode(
      digest(coalesce(public.hoof_request_header('x-hoof-session'), ''), 'sha256'),
      'hex'
    )
    and session.device_id = coalesce(public.hoof_request_header('x-hoof-device-id'), '')
    and session.revoked_at is null
    and session.expires_at > now()
  order by session.created_at desc
  limit 1;
$$;

create or replace function public.hoof_session_employee_id()
returns uuid
language sql
stable
security definer
set search_path = public, extensions
as $$
  select employee_id from public.hoof_current_session() limit 1;
$$;

create or replace function public.hoof_session_client_id()
returns uuid
language sql
stable
security definer
set search_path = public, extensions
as $$
  select client_id from public.hoof_current_session() limit 1;
$$;

create or replace function public.hoof_session_device_id()
returns text
language sql
stable
security definer
set search_path = public, extensions
as $$
  select device_id from public.hoof_current_session() limit 1;
$$;

create or replace function public.hoof_session_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select coalesce((
    select employee.is_admin
    from public.employees employee
    where employee.id = public.hoof_session_employee_id()
      and employee.status = 'active'
  ), false);
$$;

create or replace function public.hoof_session_can_access_farm(target_farm_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1
    from public.hoof_current_session() session
    join public.employee_farms assignment on assignment.employee_id = session.employee_id
    join public.farms farm on farm.id = assignment.farm_id
    join public.clients client on client.id = session.client_id
    join public.employees employee on employee.id = session.employee_id
    where assignment.farm_id = target_farm_id
      and farm.client_id = session.client_id
      and farm.status = 'active'
      and client.status = 'active'
      and employee.client_id = session.client_id
      and employee.status = 'active'
      and exists (
        select 1 from public.licenses license
        where license.farm_id = target_farm_id
          and license.status = 'active'
          and (license.starts_at is null or license.starts_at <= now())
          and (license.expires_at is null or license.expires_at >= now())
      )
      and exists (
        select 1 from public.devices device
        where device.farm_id = target_farm_id
          and device.employee_id = session.employee_id
          and device.device_id = session.device_id
          and device.status = 'active'
      )
  );
$$;

create or replace function public.hoof_storage_farm_id(object_name text)
returns uuid
language plpgsql
immutable
as $$
declare
  folders text[];
begin
  folders := storage.foldername(object_name);
  if array_length(folders, 1) < 2 or folders[1] <> 'farms' then
    return null;
  end if;
  return folders[2]::uuid;
exception when others then
  return null;
end;
$$;

revoke all on function public.hoof_current_session() from public;
grant execute on function public.hoof_request_header(text) to anon, authenticated;
grant execute on function public.hoof_session_employee_id() to anon, authenticated;
grant execute on function public.hoof_session_client_id() to anon, authenticated;
grant execute on function public.hoof_session_device_id() to anon, authenticated;
grant execute on function public.hoof_session_is_admin() to anon, authenticated;
grant execute on function public.hoof_session_can_access_farm(uuid) to anon, authenticated;
grant execute on function public.hoof_storage_farm_id(text) to anon, authenticated;

create or replace function public.protect_hoof_visit_audit_fields()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  session_employee_id uuid;
  session_employee_name text;
begin
  if tg_op = 'INSERT' then
    session_employee_id := public.hoof_session_employee_id();
    select name into session_employee_name
    from public.employees where id = session_employee_id;
    if session_employee_id is null or session_employee_name is null then
      raise exception 'Sessão de funcionário inválida';
    end if;
    new.employee_id := session_employee_id;
    new.employee_name := session_employee_name;
    new.device_id := public.hoof_session_device_id();
    return new;
  end if;

  if new.farm_id is distinct from old.farm_id
     or new.created_at is distinct from old.created_at
     or new.date is distinct from old.date
     or new.employee_id is distinct from old.employee_id
     or new.employee_name is distinct from old.employee_name
     or new.device_id is distinct from old.device_id then
    raise exception 'Campos de auditoria da visita são imutáveis';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists protect_hoof_visit_audit_fields on public.hoof_visits;
create trigger protect_hoof_visit_audit_fields
before insert or update on public.hoof_visits
for each row execute function public.protect_hoof_visit_audit_fields();

create or replace function public.reject_hoof_immutable_change()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Registro auditável não pode ser alterado ou excluído';
end;
$$;

drop trigger if exists protect_hoof_corrections on public.hoof_corrections;
create trigger protect_hoof_corrections
before update or delete on public.hoof_corrections
for each row execute function public.reject_hoof_immutable_change();

drop trigger if exists protect_hoof_admin_audit on public.hoof_admin_audit;
create trigger protect_hoof_admin_audit
before update or delete on public.hoof_admin_audit
for each row execute function public.reject_hoof_immutable_change();

create or replace function public.resolve_hoof_client(p_activation_code text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select to_jsonb(client)
  from (
    select id, name, activation_code, status, max_devices, grace_period_days
    from public.clients
    where activation_code = upper(trim(p_activation_code))
    limit 1
  ) client;
$$;

create or replace function public.validate_hoof_session()
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_session public.employee_sessions%rowtype;
begin
  select * into selected_session from public.hoof_current_session() limit 1;
  if selected_session.id is null then
    return jsonb_build_object('ok', false);
  end if;

  update public.employee_sessions
  set last_seen_at = now()
  where id = selected_session.id;

  return jsonb_build_object(
    'ok', true,
    'employee_id', selected_session.employee_id,
    'client_id', selected_session.client_id,
    'expires_at', selected_session.expires_at
  );
end;
$$;

create or replace function public.activate_hoof_device(
  p_farm_id uuid,
  p_device_name text default 'Navegador'
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_session public.employee_sessions%rowtype;
  selected_farm public.farms%rowtype;
  selected_client public.clients%rowtype;
  selected_license public.licenses%rowtype;
  existing_device public.devices%rowtype;
  active_farm_devices integer;
  active_client_devices integer;
begin
  select * into selected_session from public.hoof_current_session() limit 1;
  if selected_session.id is null then
    return jsonb_build_object('ok', false, 'message', 'Sessão expirada. Entre novamente.');
  end if;

  select * into selected_farm
  from public.farms
  where id = p_farm_id
    and client_id = selected_session.client_id
    and status = 'active';
  if selected_farm.id is null or not exists (
    select 1 from public.employee_farms assignment
    where assignment.employee_id = selected_session.employee_id
      and assignment.farm_id = p_farm_id
  ) then
    return jsonb_build_object('ok', false, 'message', 'Funcionário sem acesso a esta fazenda.');
  end if;

  select * into selected_client
  from public.clients
  where id = selected_session.client_id
    and status = 'active';
  if selected_client.id is null then
    return jsonb_build_object('ok', false, 'message', 'Empresa bloqueada ou inativa.');
  end if;

  select * into selected_license
  from public.licenses
  where farm_id = p_farm_id
    and status = 'active'
    and (starts_at is null or starts_at <= now())
    and (expires_at is null or expires_at >= now())
  order by expires_at desc nulls first
  limit 1;
  if selected_license.id is null then
    return jsonb_build_object('ok', false, 'message', 'Licença expirada ou bloqueada.');
  end if;

  select * into existing_device
  from public.devices
  where farm_id = p_farm_id
    and device_id = selected_session.device_id
  limit 1;
  if existing_device.id is not null and existing_device.status = 'blocked' then
    return jsonb_build_object('ok', false, 'message', 'Este aparelho foi bloqueado.');
  end if;

  if existing_device.id is null then
    select count(*) into active_farm_devices
    from public.devices
    where farm_id = p_farm_id and status = 'active';
    if selected_farm.max_devices is not null
       and active_farm_devices >= selected_farm.max_devices then
      return jsonb_build_object('ok', false, 'message', 'Limite de aparelhos desta fazenda atingido.');
    end if;

    select count(*) into active_client_devices
    from public.devices device
    join public.farms farm on farm.id = device.farm_id
    where farm.client_id = selected_session.client_id
      and device.status = 'active';
    if selected_client.max_devices is not null
       and active_client_devices >= selected_client.max_devices then
      return jsonb_build_object('ok', false, 'message', 'Limite de aparelhos da empresa atingido.');
    end if;
  end if;

  insert into public.devices (
    farm_id, employee_id, device_id, device_name, status, last_seen_at
  ) values (
    p_farm_id,
    selected_session.employee_id,
    selected_session.device_id,
    left(coalesce(nullif(trim(p_device_name), ''), 'Navegador'), 120),
    'active',
    now()
  )
  on conflict (farm_id, device_id) do update
  set employee_id = excluded.employee_id,
      device_name = excluded.device_name,
      last_seen_at = now();

  return jsonb_build_object(
    'ok', true,
    'license_starts_at', selected_license.starts_at,
    'license_expires_at', selected_license.expires_at
  );
end;
$$;

create or replace function public.validate_hoof_access(p_farm_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_session public.employee_sessions%rowtype;
  selected_employee public.employees%rowtype;
  selected_farm public.farms%rowtype;
  selected_device public.devices%rowtype;
  selected_license public.licenses%rowtype;
begin
  select * into selected_session from public.hoof_current_session() limit 1;
  if selected_session.id is null then
    return jsonb_build_object('ok', false, 'message', 'Sessão expirada. Entre novamente.');
  end if;

  select * into selected_employee
  from public.employees
  where id = selected_session.employee_id
    and client_id = selected_session.client_id
    and status = 'active';
  if selected_employee.id is null then
    return jsonb_build_object('ok', false, 'message', 'Funcionário bloqueado ou inativo.');
  end if;

  select * into selected_farm
  from public.farms
  where id = p_farm_id
    and client_id = selected_session.client_id
    and status = 'active';
  if selected_farm.id is null or not public.hoof_session_can_access_farm(p_farm_id) then
    return jsonb_build_object('ok', false, 'message', 'Acesso a esta fazenda foi removido.');
  end if;

  select * into selected_device
  from public.devices
  where farm_id = p_farm_id
    and device_id = selected_session.device_id
    and employee_id = selected_session.employee_id
    and status = 'active';
  if selected_device.id is null then
    return jsonb_build_object('ok', false, 'message', 'Aparelho bloqueado ou não ativado.');
  end if;

  select * into selected_license
  from public.licenses
  where farm_id = p_farm_id
    and status = 'active'
    and (starts_at is null or starts_at <= now())
    and (expires_at is null or expires_at >= now())
  order by expires_at desc nulls first
  limit 1;
  if selected_license.id is null then
    return jsonb_build_object('ok', false, 'message', 'Licença expirada ou bloqueada.');
  end if;

  update public.employee_sessions set last_seen_at = now() where id = selected_session.id;
  update public.devices set last_seen_at = now() where id = selected_device.id;

  return jsonb_build_object(
    'ok', true,
    'employee', jsonb_build_object(
      'id', selected_employee.id,
      'farm_id', selected_employee.farm_id,
      'client_id', selected_employee.client_id,
      'employee_code', selected_employee.employee_code,
      'login_name', selected_employee.login_name,
      'name', selected_employee.name,
      'status', selected_employee.status,
      'is_admin', selected_employee.is_admin
    ),
    'farm', jsonb_build_object(
      'id', selected_farm.id,
      'name', selected_farm.name,
      'client_id', selected_farm.client_id,
      'status', selected_farm.status,
      'max_devices', selected_farm.max_devices,
      'grace_period_days', selected_farm.grace_period_days
    ),
    'license_expires_at', selected_license.expires_at
  );
end;
$$;

create or replace function public.authenticate_hoof_employee(
  p_activation_code text,
  p_login text,
  p_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_client public.clients%rowtype;
  selected_employee public.employees%rowtype;
  allowed_farms jsonb;
  raw_session_token text;
  session_expires_at timestamptz := now() + interval '30 days';
  request_device_id text := coalesce(nullif(public.hoof_request_header('x-hoof-device-id'), ''), gen_random_uuid()::text);
  request_ip_hash text := encode(
    digest(coalesce(split_part(public.hoof_request_header('x-forwarded-for'), ',', 1), 'unknown'), 'sha256'),
    'hex'
  );
  normalized_login text := lower(trim(p_login));
  recent_failures integer;
begin
  delete from public.hoof_manager_sessions where expires_at < now() - interval '1 day';
  delete from public.employee_sessions
  where (expires_at < now() - interval '30 days')
     or (revoked_at is not null and revoked_at < now() - interval '30 days');
  delete from public.hoof_login_attempts where attempted_at < now() - interval '24 hours';

  select * into selected_client
  from public.clients
  where activation_code = upper(trim(p_activation_code))
    and status = 'active'
  limit 1;

  if selected_client.id is null then
    return null;
  end if;

  select count(*) into recent_failures
  from public.hoof_login_attempts
  where client_id = selected_client.id
    and login_key = normalized_login
    and ip_hash = request_ip_hash
    and success = false
    and attempted_at > now() - interval '15 minutes';

  if recent_failures >= 8 then
    return jsonb_build_object(
      'error', 'too_many_attempts',
      'message', 'Muitas tentativas. Aguarde 15 minutos e tente novamente.'
    );
  end if;

  select * into selected_employee
  from public.employees
  where client_id = selected_client.id
    and status = 'active'
    and (
      lower(login_name) = normalized_login
      or employee_code = trim(p_login)
    )
    and password_hash is not null
    and password_hash = crypt(p_password, password_hash)
  limit 1;

  if selected_employee.id is null then
    insert into public.hoof_login_attempts (client_id, login_key, ip_hash, success)
    values (selected_client.id, normalized_login, request_ip_hash, false);
    return null;
  end if;

  select coalesce(jsonb_agg(to_jsonb(farm) order by farm.name), '[]'::jsonb)
  into allowed_farms
  from public.employee_farms assignment
  join public.farms farm on farm.id = assignment.farm_id
  where assignment.employee_id = selected_employee.id
    and farm.client_id = selected_client.id
    and farm.status = 'active'
    and exists (
      select 1
      from public.licenses license
      where license.farm_id = farm.id
        and license.status = 'active'
        and (license.starts_at is null or license.starts_at <= now())
        and (license.expires_at is null or license.expires_at >= now())
    );

  if jsonb_array_length(allowed_farms) = 0 then
    return jsonb_build_object(
      'error', 'no_active_farm',
      'message', 'Nenhuma fazenda com licença ativa está vinculada a este funcionário.'
    );
  end if;

  update public.employee_sessions
  set revoked_at = now()
  where employee_id = selected_employee.id
    and device_id = request_device_id
    and revoked_at is null;

  raw_session_token := encode(gen_random_bytes(32), 'hex');
  insert into public.employee_sessions (
    token_hash, client_id, employee_id, device_id, expires_at
  ) values (
    encode(digest(raw_session_token, 'sha256'), 'hex'),
    selected_client.id,
    selected_employee.id,
    request_device_id,
    session_expires_at
  );

  delete from public.hoof_login_attempts
  where client_id = selected_client.id
    and login_key = normalized_login
    and ip_hash = request_ip_hash;

  return jsonb_build_object(
    'client', jsonb_build_object(
      'id', selected_client.id,
      'name', selected_client.name,
      'activation_code', selected_client.activation_code,
      'status', selected_client.status,
      'max_devices', selected_client.max_devices,
      'grace_period_days', selected_client.grace_period_days
    ),
    'employee', jsonb_build_object(
      'id', selected_employee.id,
      'farm_id', selected_employee.farm_id,
      'client_id', selected_employee.client_id,
      'employee_code', selected_employee.employee_code,
      'login_name', selected_employee.login_name,
      'name', selected_employee.name,
      'status', selected_employee.status,
      'is_admin', selected_employee.is_admin
    ),
    'farms', allowed_farms,
    'session_token', raw_session_token,
    'session_expires_at', session_expires_at
  );
end;
$$;

create or replace function public.hoof_current_manager(manager_token text)
returns setof public.hoof_manager_sessions
language sql
stable
security definer
set search_path = public, extensions
as $$
  select manager.*
  from public.hoof_manager_sessions manager
  join public.hoof_current_session() session
    on session.id = manager.employee_session_id
  where manager.token_hash = encode(digest(coalesce(manager_token, ''), 'sha256'), 'hex')
    and manager.revoked_at is null
    and manager.expires_at > now()
  order by manager.created_at desc
  limit 1;
$$;

create or replace function public.authenticate_hoof_manager(p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_session public.employee_sessions%rowtype;
  selected_employee public.employees%rowtype;
  raw_manager_token text;
  manager_expires_at timestamptz := now() + interval '15 minutes';
  request_ip_hash text := encode(
    digest(coalesce(split_part(public.hoof_request_header('x-forwarded-for'), ',', 1), 'unknown'), 'sha256'),
    'hex'
  );
  attempt_key text;
  recent_failures integer;
begin
  select * into selected_session from public.hoof_current_session() limit 1;
  if selected_session.id is null then
    return jsonb_build_object('ok', false, 'message', 'Sessão expirada. Entre novamente.');
  end if;

  select * into selected_employee
  from public.employees
  where id = selected_session.employee_id
    and client_id = selected_session.client_id
    and status = 'active'
    and is_admin = true;
  if selected_employee.id is null then
    return jsonb_build_object('ok', false, 'message', 'Este funcionário não é administrador.');
  end if;
  if not exists (
    select 1
    from public.devices device
    join public.farms farm on farm.id = device.farm_id
    where device.employee_id = selected_session.employee_id
      and device.device_id = selected_session.device_id
      and device.status = 'active'
      and farm.client_id = selected_session.client_id
      and farm.status = 'active'
  ) then
    return jsonb_build_object('ok', false, 'message', 'Ative este aparelho em uma fazenda antes de administrar.');
  end if;

  attempt_key := 'manager:' || selected_employee.id::text;
  select count(*) into recent_failures
  from public.hoof_login_attempts
  where client_id = selected_session.client_id
    and login_key = attempt_key
    and ip_hash = request_ip_hash
    and success = false
    and attempted_at > now() - interval '15 minutes';
  if recent_failures >= 5 then
    return jsonb_build_object(
      'ok', false,
      'message', 'Muitas tentativas. Aguarde 15 minutos e tente novamente.'
    );
  end if;

  if selected_employee.password_hash is null
     or selected_employee.password_hash <> crypt(p_password, selected_employee.password_hash) then
    insert into public.hoof_login_attempts (client_id, login_key, ip_hash, success)
    values (selected_session.client_id, attempt_key, request_ip_hash, false);
    return jsonb_build_object('ok', false, 'message', 'PIN incorreto.');
  end if;

  update public.hoof_manager_sessions
  set revoked_at = now()
  where employee_session_id = selected_session.id and revoked_at is null;

  raw_manager_token := encode(gen_random_bytes(32), 'hex');
  insert into public.hoof_manager_sessions (
    token_hash, employee_session_id, expires_at
  ) values (
    encode(digest(raw_manager_token, 'sha256'), 'hex'),
    selected_session.id,
    manager_expires_at
  );

  delete from public.hoof_login_attempts
  where client_id = selected_session.client_id
    and login_key = attempt_key
    and ip_hash = request_ip_hash;

  insert into public.hoof_admin_audit (client_id, employee_id, action)
  values (selected_session.client_id, selected_employee.id, 'manager_session_started');

  return jsonb_build_object(
    'ok', true,
    'manager_token', raw_manager_token,
    'expires_at', manager_expires_at
  );
end;
$$;

create or replace function public.change_hoof_employee_pin(
  p_employee_id uuid,
  p_current_pin text,
  p_new_pin text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_session public.employee_sessions%rowtype;
  selected_employee public.employees%rowtype;
  request_ip_hash text := encode(
    digest(coalesce(split_part(public.hoof_request_header('x-forwarded-for'), ',', 1), 'unknown'), 'sha256'),
    'hex'
  );
  attempt_key text;
  recent_failures integer;
begin
  select * into selected_session from public.hoof_current_session() limit 1;
  if selected_session.id is null then
    return jsonb_build_object('ok', false, 'message', 'Sessão expirada. Entre novamente.');
  end if;
  if p_employee_id <> selected_session.employee_id then
    return jsonb_build_object('ok', false, 'message', 'Você só pode alterar o próprio PIN.');
  end if;
  if p_current_pin !~ '^[0-9]{4,6}$' or p_new_pin !~ '^[0-9]{4,6}$' then
    return jsonb_build_object('ok', false, 'message', 'O PIN deve ter de 4 a 6 números.');
  end if;
  if p_current_pin = p_new_pin then
    return jsonb_build_object('ok', false, 'message', 'Escolha um PIN diferente do atual.');
  end if;

  attempt_key := 'pin-change:' || selected_session.employee_id::text;
  select count(*) into recent_failures
  from public.hoof_login_attempts
  where client_id = selected_session.client_id
    and login_key = attempt_key
    and ip_hash = request_ip_hash
    and success = false
    and attempted_at > now() - interval '15 minutes';
  if recent_failures >= 5 then
    return jsonb_build_object(
      'ok', false,
      'message', 'Muitas tentativas. Aguarde 15 minutos e tente novamente.'
    );
  end if;

  select * into selected_employee
  from public.employees
  where id = selected_session.employee_id
    and client_id = selected_session.client_id
    and status = 'active';
  if selected_employee.id is null
     or selected_employee.password_hash is null
     or selected_employee.password_hash <> crypt(p_current_pin, selected_employee.password_hash) then
    insert into public.hoof_login_attempts (client_id, login_key, ip_hash, success)
    values (selected_session.client_id, attempt_key, request_ip_hash, false);
    return jsonb_build_object('ok', false, 'message', 'PIN atual incorreto.');
  end if;

  update public.employees
  set password_hash = crypt(p_new_pin, gen_salt('bf', 12)), updated_at = now()
  where id = selected_employee.id;
  update public.employee_sessions
  set revoked_at = now()
  where employee_id = selected_employee.id
    and id <> selected_session.id
    and revoked_at is null;
  delete from public.hoof_login_attempts
  where client_id = selected_session.client_id
    and login_key = attempt_key
    and ip_hash = request_ip_hash;

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.hoof_employee_agenda()
returns setof public.hoof_visits
language sql
stable
security definer
set search_path = public, extensions
as $$
  select visit.*
  from public.hoof_current_session() session
  join public.employee_farms assignment on assignment.employee_id = session.employee_id
  join public.farms farm on farm.id = assignment.farm_id
  join public.hoof_visits visit
    on visit.farm_id = farm.id and visit.employee_id = session.employee_id
  where farm.client_id = session.client_id
    and farm.status = 'active'
    and exists (
      select 1 from public.licenses license
      where license.farm_id = farm.id
        and license.status = 'active'
        and (license.starts_at is null or license.starts_at <= now())
        and (license.expires_at is null or license.expires_at >= now())
    )
  order by visit.created_at desc;
$$;

create or replace function public.hoof_admin_overview(p_manager_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_session public.employee_sessions%rowtype;
  manager_session public.hoof_manager_sessions%rowtype;
  result jsonb;
begin
  select * into selected_session from public.hoof_current_session() limit 1;
  select * into manager_session from public.hoof_current_manager(p_manager_token) limit 1;
  if selected_session.id is null or manager_session.id is null then
    return jsonb_build_object('ok', false, 'message', 'Acesso gerente expirado.');
  end if;
  if not public.hoof_session_is_admin() then
    return jsonb_build_object('ok', false, 'message', 'Permissão de administrador removida.');
  end if;

  select jsonb_build_object(
    'ok', true,
    'farms', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', farm.id,
        'name', farm.name,
        'status', farm.status,
        'max_devices', farm.max_devices,
        'grace_period_days', farm.grace_period_days,
        'created_at', farm.created_at
      ) order by farm.name)
      from public.farms farm
      where farm.client_id = selected_session.client_id
    ), '[]'::jsonb),
    'employees', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', employee.id,
        'name', employee.name,
        'login_name', employee.login_name,
        'employee_code', employee.employee_code,
        'status', employee.status,
        'is_admin', employee.is_admin,
        'farm_ids', coalesce((
          select jsonb_agg(assignment.farm_id order by assignment.created_at)
          from public.employee_farms assignment
          where assignment.employee_id = employee.id
        ), '[]'::jsonb),
        'created_at', employee.created_at
      ) order by employee.name)
      from public.employees employee
      where employee.client_id = selected_session.client_id
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', device.id,
        'farm_id', device.farm_id,
        'employee_id', device.employee_id,
        'device_name', device.device_name,
        'status', device.status,
        'last_seen_at', device.last_seen_at,
        'created_at', device.created_at
      ) order by device.last_seen_at desc nulls last)
      from public.devices device
      join public.farms farm on farm.id = device.farm_id
      where farm.client_id = selected_session.client_id
    ), '[]'::jsonb),
    'licenses', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', license.id,
        'farm_id', license.farm_id,
        'status', license.status,
        'starts_at', license.starts_at,
        'expires_at', license.expires_at,
        'updated_at', license.updated_at
      ) order by license.created_at desc)
      from public.licenses license
      join public.farms farm on farm.id = license.farm_id
      where farm.client_id = selected_session.client_id
    ), '[]'::jsonb),
    'audit', coalesce((
      select jsonb_agg(to_jsonb(log_entry) order by log_entry.created_at desc)
      from (
        select audit.id, audit.employee_id, audit.action, audit.target_type,
               audit.target_id, audit.details, audit.created_at
        from public.hoof_admin_audit audit
        where audit.client_id = selected_session.client_id
        order by audit.created_at desc
        limit 50
      ) log_entry
    ), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.hoof_admin_action(
  p_manager_token text,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  selected_session public.employee_sessions%rowtype;
  manager_session public.hoof_manager_sessions%rowtype;
  target_farm public.farms%rowtype;
  target_employee public.employees%rowtype;
  target_device public.devices%rowtype;
  target_license public.licenses%rowtype;
  created_id uuid;
  target_id text;
  clean_name text;
  clean_login text;
  clean_code text;
  clean_pin text;
  next_status text;
begin
  select * into selected_session from public.hoof_current_session() limit 1;
  select * into manager_session from public.hoof_current_manager(p_manager_token) limit 1;
  if selected_session.id is null or manager_session.id is null then
    return jsonb_build_object('ok', false, 'message', 'Acesso gerente expirado.');
  end if;

  if not public.hoof_session_is_admin() then
    return jsonb_build_object('ok', false, 'message', 'Permissão de administrador removida.');
  end if;

  if p_action = 'create_farm' then
    clean_name := trim(coalesce(p_payload ->> 'name', ''));
    if length(clean_name) < 2 or length(clean_name) > 80 then
      return jsonb_build_object('ok', false, 'message', 'Informe um nome de fazenda válido.');
    end if;
    insert into public.farms (
      client_id, name, activation_code, status, max_devices, grace_period_days
    ) values (
      selected_session.client_id,
      clean_name,
      null,
      'active',
      greatest(1, least(100, coalesce((p_payload ->> 'max_devices')::integer, 10))),
      greatest(0, least(30, coalesce((p_payload ->> 'grace_period_days')::integer, 7)))
    ) returning id into created_id;
    insert into public.licenses (farm_id, status, starts_at, expires_at)
    values (created_id, 'active', now(), now() + interval '15 days');
    insert into public.employee_farms (employee_id, farm_id)
    values (selected_session.employee_id, created_id) on conflict do nothing;
    target_id := created_id::text;

  elsif p_action = 'create_employee' then
    clean_name := trim(coalesce(p_payload ->> 'name', ''));
    clean_login := trim(coalesce(p_payload ->> 'login_name', ''));
    clean_code := trim(coalesce(p_payload ->> 'employee_code', ''));
    clean_pin := coalesce(p_payload ->> 'pin', '');
    select * into target_farm
    from public.farms
    where id = (p_payload ->> 'farm_id')::uuid
      and client_id = selected_session.client_id;
    if target_farm.id is null then
      return jsonb_build_object('ok', false, 'message', 'Fazenda inválida.');
    end if;
    if length(clean_name) < 2 or length(clean_login) < 2 or length(clean_code) < 1 then
      return jsonb_build_object('ok', false, 'message', 'Preencha nome, login e código.');
    end if;
    if clean_pin !~ '^[0-9]{4,6}$' then
      return jsonb_build_object('ok', false, 'message', 'O PIN deve ter de 4 a 6 números.');
    end if;
    insert into public.employees (
      farm_id, client_id, employee_code, login_name, password_hash, name, status, is_admin
    ) values (
      target_farm.id,
      selected_session.client_id,
      clean_code,
      clean_login,
      crypt(clean_pin, gen_salt('bf', 12)),
      clean_name,
      'active',
      coalesce((p_payload ->> 'is_admin')::boolean, false)
    ) returning id into created_id;
    insert into public.employee_farms (employee_id, farm_id) values (created_id, target_farm.id);
    target_id := created_id::text;

  elsif p_action = 'update_employee' then
    select * into target_employee
    from public.employees
    where id = (p_payload ->> 'employee_id')::uuid
      and client_id = selected_session.client_id;
    if target_employee.id is null then
      return jsonb_build_object('ok', false, 'message', 'Funcionário inválido.');
    end if;
    next_status := coalesce(p_payload ->> 'status', target_employee.status);
    if next_status not in ('active', 'blocked') then
      return jsonb_build_object('ok', false, 'message', 'Status inválido.');
    end if;
    if target_employee.id = selected_session.employee_id
       and (next_status = 'blocked' or coalesce((p_payload ->> 'is_admin')::boolean, true) = false) then
      return jsonb_build_object('ok', false, 'message', 'Você não pode bloquear ou remover seu próprio acesso gerente.');
    end if;
    update public.employees
    set status = next_status,
        is_admin = coalesce((p_payload ->> 'is_admin')::boolean, is_admin),
        updated_at = now()
    where id = target_employee.id;
    target_id := target_employee.id::text;

  elsif p_action = 'reset_employee_pin' then
    clean_pin := coalesce(p_payload ->> 'pin', '');
    if clean_pin !~ '^[0-9]{4,6}$' then
      return jsonb_build_object('ok', false, 'message', 'O PIN deve ter de 4 a 6 números.');
    end if;
    select * into target_employee
    from public.employees
    where id = (p_payload ->> 'employee_id')::uuid
      and client_id = selected_session.client_id;
    if target_employee.id is null then
      return jsonb_build_object('ok', false, 'message', 'Funcionário inválido.');
    end if;
    update public.employees
    set password_hash = crypt(clean_pin, gen_salt('bf', 12)), updated_at = now()
    where id = target_employee.id;
    update public.employee_sessions set revoked_at = now()
    where employee_id = target_employee.id and revoked_at is null;
    target_id := target_employee.id::text;

  elsif p_action = 'assign_employee_farm' then
    select * into target_employee
    from public.employees
    where id = (p_payload ->> 'employee_id')::uuid
      and client_id = selected_session.client_id;
    select * into target_farm
    from public.farms
    where id = (p_payload ->> 'farm_id')::uuid
      and client_id = selected_session.client_id;
    if target_employee.id is null or target_farm.id is null then
      return jsonb_build_object('ok', false, 'message', 'Funcionário ou fazenda inválidos.');
    end if;
    if coalesce((p_payload ->> 'assigned')::boolean, true) then
      insert into public.employee_farms (employee_id, farm_id)
      values (target_employee.id, target_farm.id) on conflict do nothing;
    else
      if target_employee.farm_id = target_farm.id then
        return jsonb_build_object('ok', false, 'message', 'A fazenda principal não pode ser removida.');
      end if;
      delete from public.employee_farms
      where employee_id = target_employee.id and farm_id = target_farm.id;
    end if;
    target_id := target_employee.id::text;

  elsif p_action = 'update_device_status' then
    select device.* into target_device
    from public.devices device
    join public.farms farm on farm.id = device.farm_id
    where device.id = (p_payload ->> 'device_id')::uuid
      and farm.client_id = selected_session.client_id;
    next_status := coalesce(p_payload ->> 'status', 'blocked');
    if target_device.id is null or next_status not in ('active', 'blocked') then
      return jsonb_build_object('ok', false, 'message', 'Aparelho ou status inválido.');
    end if;
    update public.devices set status = next_status, updated_at = now() where id = target_device.id;
    if next_status = 'blocked' then
      update public.employee_sessions set revoked_at = now()
      where client_id = selected_session.client_id
        and device_id = target_device.device_id
        and revoked_at is null;
    end if;
    target_id := target_device.id::text;

  elsif p_action = 'update_license_status' then
    if not exists (
      select 1 from public.employees employee
      where employee.id = selected_session.employee_id
        and employee.is_platform_admin = true
    ) then
      return jsonb_build_object('ok', false, 'message', 'A licença é gerenciada pelo fornecedor do sistema.');
    end if;
    select license.* into target_license
    from public.licenses license
    join public.farms farm on farm.id = license.farm_id
    where license.id = (p_payload ->> 'license_id')::uuid
      and farm.client_id = selected_session.client_id;
    next_status := coalesce(p_payload ->> 'status', 'blocked');
    if target_license.id is null or next_status not in ('active', 'blocked', 'expired') then
      return jsonb_build_object('ok', false, 'message', 'Licença ou status inválido.');
    end if;
    update public.licenses
    set status = next_status,
        expires_at = case
          when p_payload ? 'expires_at'
            then nullif(p_payload ->> 'expires_at', '')::timestamptz
          else expires_at
        end,
        updated_at = now()
    where id = target_license.id;
    target_id := target_license.id::text;

  elsif p_action = 'update_farm' then
    select * into target_farm
    from public.farms
    where id = (p_payload ->> 'farm_id')::uuid
      and client_id = selected_session.client_id;
    if target_farm.id is null then
      return jsonb_build_object('ok', false, 'message', 'Fazenda inválida.');
    end if;
    next_status := coalesce(p_payload ->> 'status', target_farm.status);
    if next_status not in ('active', 'blocked', 'expired') then
      return jsonb_build_object('ok', false, 'message', 'Status inválido.');
    end if;
    update public.farms
    set name = coalesce(nullif(trim(p_payload ->> 'name'), ''), name),
        status = next_status,
        max_devices = greatest(1, least(100, coalesce((p_payload ->> 'max_devices')::integer, max_devices))),
        updated_at = now()
    where id = target_farm.id;
    target_id := target_farm.id::text;
  else
    return jsonb_build_object('ok', false, 'message', 'Ação administrativa inválida.');
  end if;

  insert into public.hoof_admin_audit (
    client_id, employee_id, action, target_type, target_id, details
  ) values (
    selected_session.client_id,
    selected_session.employee_id,
    p_action,
    split_part(p_action, '_', 2),
    target_id,
    p_payload - 'pin'
  );
  return jsonb_build_object('ok', true, 'id', target_id);
exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'message', 'Login ou código já cadastrado nesta empresa.');
  when invalid_text_representation then
    return jsonb_build_object('ok', false, 'message', 'Dados inválidos. Revise os campos.');
end;
$$;

revoke all on function public.resolve_hoof_client(text) from public;
revoke all on function public.validate_hoof_session() from public;
revoke all on function public.activate_hoof_device(uuid, text) from public;
revoke all on function public.validate_hoof_access(uuid) from public;
revoke all on function public.authenticate_hoof_employee(text, text, text) from public;
revoke all on function public.hoof_current_manager(text) from public;
revoke all on function public.authenticate_hoof_manager(text) from public;
revoke all on function public.change_hoof_employee_pin(uuid, text, text) from public;
revoke all on function public.hoof_employee_agenda() from public;
revoke all on function public.hoof_admin_overview(text) from public;
revoke all on function public.hoof_admin_action(text, text, jsonb) from public;
grant execute on function public.resolve_hoof_client(text) to anon, authenticated;
grant execute on function public.validate_hoof_session() to anon, authenticated;
grant execute on function public.activate_hoof_device(uuid, text) to anon, authenticated;
grant execute on function public.validate_hoof_access(uuid) to anon, authenticated;
grant execute on function public.authenticate_hoof_employee(text, text, text) to anon, authenticated;
grant execute on function public.authenticate_hoof_manager(text) to anon, authenticated;
grant execute on function public.change_hoof_employee_pin(uuid, text, text) to anon, authenticated;
grant execute on function public.hoof_employee_agenda() to anon, authenticated;
grant execute on function public.hoof_admin_overview(text) to anon, authenticated;
grant execute on function public.hoof_admin_action(text, text, jsonb) to anon, authenticated;

update public.employees
set name = 'Sandro',
    login_name = 'Sandro',
    is_admin = true,
    updated_at = now()
where id = '30000000-0000-4000-8000-000000000001';

update public.employees
set is_admin = (id = '30000000-0000-4000-8000-000000000002'::uuid),
    updated_at = now()
where client_id = '10000000-0000-4000-8000-000000000002'::uuid;

alter table public.clients enable row level security;
alter table public.farms enable row level security;
alter table public.employees enable row level security;
alter table public.employee_farms enable row level security;
alter table public.devices enable row level security;
alter table public.licenses enable row level security;

revoke all on public.employees from anon, authenticated;
grant select (
  id, farm_id, client_id, employee_code, login_name, name,
  status, is_admin, created_at, updated_at
) on public.employees to anon, authenticated;

drop policy if exists "hoof client session read" on public.clients;
create policy "hoof client session read" on public.clients
  for select to anon, authenticated
  using (id = public.hoof_session_client_id());

drop policy if exists "hoof farm session read" on public.farms;
create policy "hoof farm session read" on public.farms
  for select to anon, authenticated
  using (public.hoof_session_can_access_farm(id));

drop policy if exists "hoof employee session read" on public.employees;
create policy "hoof employee session read" on public.employees
  for select to anon, authenticated
  using (
    id = public.hoof_session_employee_id()
    or (client_id = public.hoof_session_client_id() and public.hoof_session_is_admin())
  );

drop policy if exists "hoof assignment session read" on public.employee_farms;
create policy "hoof assignment session read" on public.employee_farms
  for select to anon, authenticated
  using (
    employee_id = public.hoof_session_employee_id()
    or (
      public.hoof_session_is_admin()
      and exists (
        select 1
        from public.employees employee
        join public.farms farm on farm.id = employee_farms.farm_id
        where employee.id = employee_farms.employee_id
          and employee.client_id = public.hoof_session_client_id()
          and farm.client_id = public.hoof_session_client_id()
      )
    )
  );

drop policy if exists "hoof license session read" on public.licenses;
create policy "hoof license session read" on public.licenses
  for select to anon, authenticated
  using (public.hoof_session_can_access_farm(farm_id));

drop policy if exists "hoof device session read" on public.devices;
drop policy if exists "hoof device session insert" on public.devices;
drop policy if exists "hoof device session update" on public.devices;
create policy "hoof device session read" on public.devices
  for select to anon, authenticated
  using (
    public.hoof_session_can_access_farm(farm_id)
    and (device_id = public.hoof_session_device_id() or public.hoof_session_is_admin())
  );
create policy "hoof device session insert" on public.devices
  for insert to anon, authenticated
  with check (
    public.hoof_session_can_access_farm(farm_id)
    and employee_id = public.hoof_session_employee_id()
    and device_id = public.hoof_session_device_id()
  );
create policy "hoof device session update" on public.devices
  for update to anon, authenticated
  using (
    public.hoof_session_can_access_farm(farm_id)
    and device_id = public.hoof_session_device_id()
  )
  with check (
    public.hoof_session_can_access_farm(farm_id)
    and employee_id = public.hoof_session_employee_id()
    and device_id = public.hoof_session_device_id()
  );

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'hoof_visits', 'hoof_feet', 'animals', 'farm_lotes',
    'hoof_media', 'hoof_corrections', 'farm_settings'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists "hoof tenant read" on public.%I', table_name);
    execute format('drop policy if exists "hoof tenant insert" on public.%I', table_name);
    execute format('drop policy if exists "hoof tenant update" on public.%I', table_name);
    execute format('drop policy if exists "hoof tenant delete" on public.%I', table_name);
    execute format(
      'create policy "hoof tenant read" on public.%I for select to anon, authenticated using (public.hoof_session_can_access_farm(farm_id))',
      table_name
    );
  end loop;
end;
$$;

create policy "hoof tenant insert" on public.hoof_visits
  for insert to anon, authenticated
  with check (
    public.hoof_session_can_access_farm(farm_id)
    and employee_id = public.hoof_session_employee_id()
  );
create policy "hoof tenant update" on public.hoof_visits
  for update to anon, authenticated
  using (
    public.hoof_session_can_access_farm(farm_id)
    and employee_id = public.hoof_session_employee_id()
  )
  with check (
    public.hoof_session_can_access_farm(farm_id)
    and employee_id = public.hoof_session_employee_id()
  );
create policy "hoof tenant delete" on public.hoof_visits
  for delete to anon, authenticated
  using (false);

do $$
declare
  table_name text;
begin
  foreach table_name in array array['hoof_feet', 'hoof_media'] loop
    execute format(
      'create policy "hoof tenant insert" on public.%I for insert to anon, authenticated with check (public.hoof_session_can_access_farm(farm_id))',
      table_name
    );
    execute format(
      'create policy "hoof tenant update" on public.%I for update to anon, authenticated using (public.hoof_session_can_access_farm(farm_id)) with check (public.hoof_session_can_access_farm(farm_id))',
      table_name
    );
    execute format(
      'create policy "hoof tenant delete" on public.%I for delete to anon, authenticated using (public.hoof_session_can_access_farm(farm_id) and public.hoof_session_is_admin())',
      table_name
    );
  end loop;
end;
$$;

create policy "hoof tenant insert" on public.hoof_corrections
  for insert to anon, authenticated
  with check (
    public.hoof_session_can_access_farm(farm_id)
    and employee_id = public.hoof_session_employee_id()
  );
create policy "hoof tenant update" on public.hoof_corrections
  for update to anon, authenticated
  using (false)
  with check (false);
create policy "hoof tenant delete" on public.hoof_corrections
  for delete to anon, authenticated
  using (false);

do $$
declare
  table_name text;
begin
  foreach table_name in array array['animals', 'farm_lotes', 'farm_settings'] loop
    execute format(
      'create policy "hoof tenant insert" on public.%I for insert to anon, authenticated with check (public.hoof_session_can_access_farm(farm_id) and public.hoof_session_is_admin())',
      table_name
    );
    execute format(
      'create policy "hoof tenant update" on public.%I for update to anon, authenticated using (public.hoof_session_can_access_farm(farm_id) and public.hoof_session_is_admin()) with check (public.hoof_session_can_access_farm(farm_id) and public.hoof_session_is_admin())',
      table_name
    );
    execute format(
      'create policy "hoof tenant delete" on public.%I for delete to anon, authenticated using (public.hoof_session_can_access_farm(farm_id) and public.hoof_session_is_admin())',
      table_name
    );
  end loop;
end;
$$;

drop policy if exists "hoof media read" on storage.objects;
drop policy if exists "hoof media insert" on storage.objects;
drop policy if exists "hoof media update" on storage.objects;
drop policy if exists "hoof media delete" on storage.objects;
drop policy if exists "hoof media tenant read" on storage.objects;
drop policy if exists "hoof media tenant insert" on storage.objects;
drop policy if exists "hoof media tenant update" on storage.objects;
drop policy if exists "hoof media tenant delete" on storage.objects;

create policy "hoof media tenant read" on storage.objects
  for select to anon, authenticated
  using (
    bucket_id = 'media'
    and public.hoof_session_can_access_farm(public.hoof_storage_farm_id(name))
  );
create policy "hoof media tenant insert" on storage.objects
  for insert to anon, authenticated
  with check (
    bucket_id = 'media'
    and public.hoof_session_can_access_farm(public.hoof_storage_farm_id(name))
  );
create policy "hoof media tenant update" on storage.objects
  for update to anon, authenticated
  using (
    bucket_id = 'media'
    and public.hoof_session_can_access_farm(public.hoof_storage_farm_id(name))
  )
  with check (
    bucket_id = 'media'
    and public.hoof_session_can_access_farm(public.hoof_storage_farm_id(name))
  );
create policy "hoof media tenant delete" on storage.objects
  for delete to anon, authenticated
  using (
    bucket_id = 'media'
    and public.hoof_session_can_access_farm(public.hoof_storage_farm_id(name))
    and public.hoof_session_is_admin()
  );
